name: Testes Automatizados

on:
  workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

  steps:
    # Step 1
    - name: Checkout
      uses: actions/checkout@v2

    # Step 2
    - name: Configurar Node.jobs
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Step 3
    - name: Instalar dependÃªncias
      run: npm install

    # Step 4
    - name: Executar Testes
      run: npm test