name: Testes Automatizados

on:
  workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1
    - name: Checkout
      uses: actions/checkout@v2

      # Step 2
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

      # Step 3
    - name: Instalar dependÃªncias
      run: |
        rm -rf node_modules
        npm ci

    - name: Debug
      run: ls -la node_modules/.bin

      # Step 4
    - name: Executar Testes
      run: npm test